title: "Yusen's Blog"
author: "Yusen Zhang"
description: "Recording research, design, and life"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%Y-%m-%d"

# Layout
show_excerpts: true        # Show article excerpts on the homepage
show_frame: true           # Display a frame on large screens
show_sidebar: false        # Hide sidebar
show_minimal: false        # Keep normal layout

# Menu
# navigation:
#   - {file: "archive.html", sidebaricon: home}
#   - {file: "README.md", sidebaricon: address-card}

# External links (shown at the top right)
external:
  - {title: Email, icon: envelope, url: "mailto:2783477z@student.gla.ac.uk"}
#   - {title: Github, icon: github, url: "https://github.com/yusenzhang"}  # updated link
#   - {title: Subscribe, icon: rss, url: "/feed.xml"}

# Comments (currently disabled, you can enable later)
comments:
#  disqus_shortname: ""
#  isso_domain: ""

# Plugins
plugins:
 - jekyll-feed
